### ISSUE TITLE
Could you provide a SSR example?

### ISSUE THREAD

**Issue by jonbjk** [systemjs/systemjs-examples#16]
Since SystemJS now includes a system-node.cjs loader, it would be nice with a SSR example that uses importMaps.

**Comment by internettrans** [comment]
Hi @jonbjk, good question. I've put together #17 which shows how to use the loader in NodeJS. It does not show server rendering of an HTML file - just module loading in NodeJS.

One thing I'll mention - I recently published an alternative implementation of import maps in NodeJS. See https://github.com/node-loader/node-loader-import-maps. That nodejs loader allows you to use import maps in Node with ES modules. I am considering creating a node-loader-system project that will allow NodeJS to understand System.register syntax without using the SystemJS loader. I plan on using those projects for the single-spa community's SSR efforts.

**Comment by jonbjk** [comment]
Hi @joeldenning
Thank you so much for the example.

The work towards the single-spa community's SSR effort sounds really interesting.

**Comment by its-dibo** [comment]
> That nodejs loader allows you to use import maps in Node with ES modules.

this is great, but if it allows dynamic importmap from JS would be nice, check out [this issue](https://github.com/node-loader/node-loader-import-maps/issues/11)
